language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
  - neo4j
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "shopping-list-1809-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
  branches:
    only:
      -master

# before_deploy:
#   - npm run build-client # make the bundle
#   - rm -rf node_modules # omit from the tarball, since we skip cleanup
# deploy:
#   skip_cleanup: true # prevents travis from deleting the build
#   provider: heroku
  app: shopping-list-1809 # see README
  api_key:
    secure: "x4jlBqUVuxSr4r/55GZVU/Uyv3dOBXMxdgVv5O8/Jl5rsdhhZCneMwEXepOCn8KnP+0o5a7/n0+KZOI523W77xCatyC/38q4aR2I4o0RA9EZwv8wv5SXeQnqKEAu7EUkut51WRNUlDPPA4P2WXXCms5h2/aSsBq084mGdIyOd13o7auvDZThmbybnBITyeV6XxKEJwj6BpelUfQicwmV6cS9CdzU8mX+F+O9VTlvusOblYvY80ia1iSFuAj3oLmaBH/mdiitq3uckP/1q1X4zpPeVjw0bjjNlmh9c9AHglzqjUVht0mGUJ31cBZ1Vd3tGGag13u9iTBoN6iiTA7Ts4ooc2b4IWHnxgtcgIlJF905dhpYpyiYD3c2ERwplRwYyMhTKE+NJUTMhesIHRc0KLoKom9VrdnjQQJ9iPHAs5Y4i4acqdeTktOBeO8+oKzxnidWBU7lVJx+Uia4G0ESROXxjbgRN/iPC+Pvsc0d8aPcDIqhuCrwGWPhYaMkhVFrCAtRqAztNyixNtp5sDCtmOSf+IcDPQVxdTiIrzHe6CxmtXI3kXJlr2EBOz7QgxQ6sA9eT/DPX19FdhFIlNSL5N7SEKeXiQ3/jgGCozE7KjP8H7pR7ieTfhU/maJuTJmCsTRs+CNEIjmHU1YwNNJYt5us7gp+gCjRZmuIJioQ4Ow=" # see README
